### ISSUE TITLE
about ページの「身につくスキル」の項目に脱字がある

### ISSUE THREAD

**Issue by unstoppa61e** [flock-team/portal#19]
# ドキュメントURL
[`https://www.flock.codes/about`](https://www.flock.codes/about#:~:text=%E8%BA%AB%E3%81%AB%E3%81%A4%E3%81%8F%E3%82%B9%E3%82%AD%E3%83%AB-,%E3%83%A1%E3%83%B3%E3%82%BF%E3%83%BC%E4%B8%BB%E3%81%AB,-%E4%BB%A5%E4%B8%8B%E3%81%AE%E3%82%88%E3%81%86)

# 内容
誤：「メンター主に」
正：「メンターは主に」

**Comment by nino-cast** [comment]
@unstoppa61e 
ありがとうございます！修正しました ✅
